services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"  # Expor a porta 10000
    environment:
      PORT: 10000
    volumes:
      - .:/var/www
     # - ./database:/var/data/database

    command: bash -c "npm run dev & php artisan serve --host 0.0.0.0 --port=10000"
